### ISSUE TITLE
Authorization Prompt Appears Repeatedly Despite Prior Authorization

### ISSUE THREAD

**Issue by Sorrow91** [wdesimini/TVCommanderKit#27]
I am experiencing an issue with the demo app where the authorization prompt appears every time I click "connect," even though the app has already been authorized. This seems to be caused by the authentication status not being consistently updated, defaulting to "none."

**Steps to Reproduce:**

- Open the demo app.
- Ensure the app is authorized on the TV.
- Click the "connect" button.
- Observe that the authorization prompt appears again.

**Expected Behavior:**
The app should recognize the existing authorization and connect without prompting for authorization again.

**Actual Behavior:**
The app prompts for authorization every time the "connect" button is clicked, even if it has already been authorized.

**Possible Cause:**
The authentication status is not being updated correctly and defaults to "none," causing the app to request authorization repeatedly.

**Additional Information:**
Please investigate why the authentication status is not being updated and ensure it reflects the correct state to prevent unnecessary authorization prompts. This template provides a structured way to report the issue, including expected and actual behavior, steps to reproduce the problem, and relevant environment details. Adjust the placeholders with specific information related to your setup.

**Comment by wdesimini** [comment]
@Sorrow91 regarding this:
- There's a chance the TV wasn't authorizing the sample app because no auth token was added for the websocket to connect. Added a way to be able to enter auth tokens in the sample app.
- There's also a chance the TV didn't authorize the app because the token was old (I've ran into this issue a couple times). I'm not 100% sure, but I think it's because the tokens expire after a while? Hard to tell...
